// <auto-generated />
using System;
using EV_BatteryChangeStation_Repository.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EV_BatteryChangeStation_Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331000943_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AccountID");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("RoleID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Battery", b =>
                {
                    b.Property<Guid>("BatteryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("BatteryID");

                    b.Property<Guid>("BatteryTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("BatteryTypeID");

                    b.Property<decimal?>("CapacityKwh")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("Capacity_kWh");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentChargeLevel")
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateOnly?>("InsuranceDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastChargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("StateOfHealth")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("StationID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BatteryId");

                    b.HasIndex("BatteryTypeId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("StationId");

                    b.ToTable("Battery", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.BatteryHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("HistoryID");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ActorAccountID");

                    b.Property<Guid>("BatteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("BatteryID");

                    b.Property<decimal?>("ChargeLevelAtTime")
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FromStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("FromStationID");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("FromVehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("FromVehicleID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("SoHAtTime")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid?>("ToStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("ToStationID");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ToVehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("ToVehicleID");

                    b.HasKey("HistoryId");

                    b.HasIndex("ActorAccountId");

                    b.HasIndex("BatteryId");

                    b.HasIndex("FromStationId");

                    b.HasIndex("FromVehicleId");

                    b.HasIndex("ToStationId");

                    b.HasIndex("ToVehicleId");

                    b.ToTable("BatteryHistory", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.BatteryReturnInspection", b =>
                {
                    b.Property<Guid>("InspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("InspectionID");

                    b.Property<Guid>("BatteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("BatteryID");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("BookingID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionNote")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NextStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhysicalCondition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("SoHPercent")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("StaffID");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("StationID");

                    b.HasKey("InspectionId");

                    b.HasIndex("BatteryId");

                    b.HasIndex("BookingId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StationId");

                    b.ToTable("BatteryReturnInspection", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.BatteryType", b =>
                {
                    b.Property<Guid>("BatteryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("BatteryTypeID");

                    b.Property<string>("BatteryTypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BatteryTypeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("CapacityKwh")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("Capacity_kWh");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Voltage")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("BatteryTypeId");

                    b.HasIndex("BatteryTypeCode")
                        .IsUnique();

                    b.ToTable("BatteryType", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("BookingID");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("AccountID");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("RequestedBatteryTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("RequestedBatteryTypeID");

                    b.Property<string>("StaffNote")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("StationID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("TargetTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("VehicleID");

                    b.HasKey("BookingId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("RequestedBatteryTypeId");

                    b.HasIndex("StationId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("FeedbackID");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("AccountID");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("BookingID");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("StationID");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionID");

                    b.HasKey("FeedbackId");

                    b.HasIndex("AccountId");

                    b.HasIndex("BookingId");

                    b.HasIndex("StationId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PaymentID");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("AccountID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("BookingID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("PaymentGatewayId")
                        .HasColumnType("bigint");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("RecordedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("RecordedByAccountID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionID");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserSubscriptionID");

                    b.HasKey("PaymentId");

                    b.HasIndex("AccountId");

                    b.HasIndex("BookingId");

                    b.HasIndex("RecordedByAccountId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("TransactionReference")
                        .IsUnique();

                    b.HasIndex("UserSubscriptionId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PermissionID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionCode")
                        .IsUnique();

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RoleID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RolePermissionID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("PermissionID");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("RoleID");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Station", b =>
                {
                    b.Property<Guid>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("StationID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentBatteryCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric(9,6)");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("OperatingHours")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StationId");

                    b.ToTable("Station", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.StationBatteryType", b =>
                {
                    b.Property<Guid>("StationBatteryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("StationBatteryTypeID");

                    b.Property<Guid>("BatteryTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("BatteryTypeID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("StationID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("StationBatteryTypeId");

                    b.HasIndex("BatteryTypeId");

                    b.HasIndex("StationId", "BatteryTypeId")
                        .IsUnique();

                    b.ToTable("StationBatteryType", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.StationInventoryLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("LogID");

                    b.Property<int>("AvailableBatteries")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AvgChargeLevel")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid?>("BatteryTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("BatteryTypeID");

                    b.Property<int>("ChargingBatteries")
                        .HasColumnType("integer");

                    b.Property<int>("InVehicleBatteries")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaintenanceBatteries")
                        .HasColumnType("integer");

                    b.Property<int>("ReservedBatteries")
                        .HasColumnType("integer");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("StationID");

                    b.HasKey("LogId");

                    b.HasIndex("BatteryTypeId");

                    b.HasIndex("StationId");

                    b.ToTable("StationInventoryLog", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.StationStaffAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AssignmentID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("StaffID");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("StationID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssignmentId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StationId");

                    b.ToTable("StationStaffAssignment", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PlanID");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ExtraFeePerSwap")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("SwapLimitPerMonth")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlanId");

                    b.HasIndex("PlanCode")
                        .IsUnique();

                    b.ToTable("SubscriptionPlan", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SupportRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RequestID");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("AccountID");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("BookingID");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("StationID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionID");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("AccountId");

                    b.HasIndex("BookingId");

                    b.HasIndex("StationId");

                    b.HasIndex("TransactionId");

                    b.ToTable("SupportRequest", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SupportRequestResponse", b =>
                {
                    b.Property<Guid>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ResponseID");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("RequestID");

                    b.Property<DateTime>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("StaffID");

                    b.Property<string>("StatusAfterResponse")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ResponseId");

                    b.HasIndex("RequestId");

                    b.HasIndex("StaffId");

                    b.ToTable("SupportRequestResponse", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SwappingTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionID");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("BookingID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("ReleasedBatteryCharge")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("ReleasedBatteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ReleasedBatteryID");

                    b.Property<decimal?>("ReleasedBatterySoH")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("ReturnedBatteryCharge")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ReturnedBatteryCondition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ReturnedBatteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ReturnedBatteryID");

                    b.Property<decimal?>("ReturnedBatterySoH")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("StaffID");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("StationID");

                    b.Property<decimal>("SwapFee")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("UsedSubscription")
                        .HasColumnType("boolean");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("VehicleID");

                    b.HasKey("TransactionId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ReleasedBatteryId");

                    b.HasIndex("ReturnedBatteryId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StationId");

                    b.HasIndex("VehicleId");

                    b.ToTable("SwappingTransaction", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("UserSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UserSubscriptionID");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("AccountID");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("PlanID");

                    b.Property<int?>("RemainingSwaps")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("VehicleID");

                    b.HasKey("UserSubscriptionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PlanId");

                    b.HasIndex("VehicleId");

                    b.ToTable("UserSubscription", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("VehicleID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentBatteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("CurrentBatteryID");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("ModelID");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("OwnerID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vin")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("VIN");

                    b.HasKey("VehicleId");

                    b.HasIndex("CurrentBatteryId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("ModelId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.VehicleModel", b =>
                {
                    b.Property<Guid>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ModelID");

                    b.Property<Guid>("BatteryTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("BatteryTypeID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Producer")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ModelId");

                    b.HasIndex("BatteryTypeId");

                    b.HasIndex("ModelName", "Producer")
                        .IsUnique();

                    b.ToTable("VehicleModel", (string)null);
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Account", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Battery", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.BatteryType", "BatteryType")
                        .WithMany("Batteries")
                        .HasForeignKey("BatteryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "Station")
                        .WithMany("Batteries")
                        .HasForeignKey("StationId");

                    b.Navigation("BatteryType");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.BatteryHistory", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "ActorAccount")
                        .WithMany("BatteryHistoryActions")
                        .HasForeignKey("ActorAccountId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Battery", "Battery")
                        .WithMany("BatteryHistories")
                        .HasForeignKey("BatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "FromStation")
                        .WithMany()
                        .HasForeignKey("FromStationId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Vehicle", "FromVehicle")
                        .WithMany("BatteryHistoryFromVehicles")
                        .HasForeignKey("FromVehicleId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "ToStation")
                        .WithMany()
                        .HasForeignKey("ToStationId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Vehicle", "ToVehicle")
                        .WithMany("BatteryHistoryToVehicles")
                        .HasForeignKey("ToVehicleId");

                    b.Navigation("ActorAccount");

                    b.Navigation("Battery");

                    b.Navigation("FromStation");

                    b.Navigation("FromVehicle");

                    b.Navigation("ToStation");

                    b.Navigation("ToVehicle");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.BatteryReturnInspection", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Battery", "Battery")
                        .WithMany("ReturnInspections")
                        .HasForeignKey("BatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Booking", "Booking")
                        .WithMany("BatteryReturnInspections")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Staff")
                        .WithMany("BatteryReturnInspections")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "Station")
                        .WithMany("BatteryReturnInspections")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battery");

                    b.Navigation("Booking");

                    b.Navigation("Staff");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Booking", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Account")
                        .WithMany("Bookings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "ApprovedByAccount")
                        .WithMany("ApprovedBookings")
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.BatteryType", "RequestedBatteryType")
                        .WithMany("RequestedBookings")
                        .HasForeignKey("RequestedBatteryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "Station")
                        .WithMany("Bookings")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ApprovedByAccount");

                    b.Navigation("RequestedBatteryType");

                    b.Navigation("Station");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Feedback", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Account")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Booking", "Booking")
                        .WithMany("Feedbacks")
                        .HasForeignKey("BookingId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "Station")
                        .WithMany("Feedbacks")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.SwappingTransaction", "Transaction")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TransactionId");

                    b.Navigation("Account");

                    b.Navigation("Booking");

                    b.Navigation("Station");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Payment", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Account")
                        .WithMany("Payments")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "RecordedByAccount")
                        .WithMany("RecordedPayments")
                        .HasForeignKey("RecordedByAccountId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.SwappingTransaction", "Transaction")
                        .WithMany("Payments")
                        .HasForeignKey("TransactionId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.UserSubscription", "UserSubscription")
                        .WithMany("Payments")
                        .HasForeignKey("UserSubscriptionId");

                    b.Navigation("Account");

                    b.Navigation("Booking");

                    b.Navigation("RecordedByAccount");

                    b.Navigation("Transaction");

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.RolePermission", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.StationBatteryType", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.BatteryType", "BatteryType")
                        .WithMany("StationBatteryTypes")
                        .HasForeignKey("BatteryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "Station")
                        .WithMany("StationBatteryTypes")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatteryType");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.StationInventoryLog", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.BatteryType", "BatteryType")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("BatteryTypeId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "Station")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatteryType");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.StationStaffAssignment", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Staff")
                        .WithMany("StationAssignments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "Station")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SupportRequest", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Account")
                        .WithMany("SupportRequests")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Booking", "Booking")
                        .WithMany("SupportRequests")
                        .HasForeignKey("BookingId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "Station")
                        .WithMany("SupportRequests")
                        .HasForeignKey("StationId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.SwappingTransaction", "Transaction")
                        .WithMany("SupportRequests")
                        .HasForeignKey("TransactionId");

                    b.Navigation("Account");

                    b.Navigation("Booking");

                    b.Navigation("Station");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SupportRequestResponse", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.SupportRequest", "Request")
                        .WithMany("Responses")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Staff")
                        .WithMany("SupportResponses")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SwappingTransaction", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Booking", "Booking")
                        .WithOne("SwappingTransaction")
                        .HasForeignKey("EV_BatteryChangeStation_Repository.Entities.SwappingTransaction", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Battery", "ReleasedBattery")
                        .WithMany("ReleasedSwapTransactions")
                        .HasForeignKey("ReleasedBatteryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Battery", "ReturnedBattery")
                        .WithMany("ReturnedSwapTransactions")
                        .HasForeignKey("ReturnedBatteryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Staff")
                        .WithMany("StaffSwapTransactions")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Station", "Station")
                        .WithMany("SwappingTransactions")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Vehicle", "Vehicle")
                        .WithMany("SwappingTransactions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ReleasedBattery");

                    b.Navigation("ReturnedBattery");

                    b.Navigation("Staff");

                    b.Navigation("Station");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.UserSubscription", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Account")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.SubscriptionPlan", "Plan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Vehicle", "Vehicle")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Plan");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Vehicle", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Battery", "CurrentBattery")
                        .WithMany("VehiclesUsingAsCurrent")
                        .HasForeignKey("CurrentBatteryId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.VehicleModel", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId");

                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.Account", "Owner")
                        .WithMany("OwnedVehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentBattery");

                    b.Navigation("Model");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.VehicleModel", b =>
                {
                    b.HasOne("EV_BatteryChangeStation_Repository.Entities.BatteryType", "BatteryType")
                        .WithMany("VehicleModels")
                        .HasForeignKey("BatteryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatteryType");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Account", b =>
                {
                    b.Navigation("ApprovedBookings");

                    b.Navigation("BatteryHistoryActions");

                    b.Navigation("BatteryReturnInspections");

                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");

                    b.Navigation("OwnedVehicles");

                    b.Navigation("Payments");

                    b.Navigation("RecordedPayments");

                    b.Navigation("StaffSwapTransactions");

                    b.Navigation("StationAssignments");

                    b.Navigation("SupportRequests");

                    b.Navigation("SupportResponses");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Battery", b =>
                {
                    b.Navigation("BatteryHistories");

                    b.Navigation("ReleasedSwapTransactions");

                    b.Navigation("ReturnInspections");

                    b.Navigation("ReturnedSwapTransactions");

                    b.Navigation("VehiclesUsingAsCurrent");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.BatteryType", b =>
                {
                    b.Navigation("Batteries");

                    b.Navigation("InventoryLogs");

                    b.Navigation("RequestedBookings");

                    b.Navigation("StationBatteryTypes");

                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Booking", b =>
                {
                    b.Navigation("BatteryReturnInspections");

                    b.Navigation("Feedbacks");

                    b.Navigation("Payments");

                    b.Navigation("SupportRequests");

                    b.Navigation("SwappingTransaction");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Role", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Station", b =>
                {
                    b.Navigation("Batteries");

                    b.Navigation("BatteryReturnInspections");

                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");

                    b.Navigation("InventoryLogs");

                    b.Navigation("StaffAssignments");

                    b.Navigation("StationBatteryTypes");

                    b.Navigation("SupportRequests");

                    b.Navigation("SwappingTransactions");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SupportRequest", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.SwappingTransaction", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Payments");

                    b.Navigation("SupportRequests");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.UserSubscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.Vehicle", b =>
                {
                    b.Navigation("BatteryHistoryFromVehicles");

                    b.Navigation("BatteryHistoryToVehicles");

                    b.Navigation("Bookings");

                    b.Navigation("SwappingTransactions");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("EV_BatteryChangeStation_Repository.Entities.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
